import { SliderItem } from "@/types/section";

export const sliderItems: SliderItem[] = [
  {
    id: 1,
    display_order: 1,
    display_type: "image",
    title: "Discover the Mountains",
    subtitle: "Adventure Awaits",
    description: "Explore breathtaking mountain landscapes and unforgettable hiking trails.",
    link: [
      {
        slider_item_id: 1,
        link: "/images/kanchenjunga.jpg",
        link_name: "Explore Now",
      },
    ],
    is_active: 1,
    image: "/images/kanchenjunga.jpg",
    image_title: "Mountain Adventure",
    video_url: null,
  },
  {
    id: 2,
    display_order: 2,
    display_type: "image",
    title: "Experience the Ocean",
    subtitle: "Feel the Breeze",
    description: "Dive into crystal-clear waters and relax on pristine beaches.",
    link: [
      {
        slider_item_id: 2,
        link: "/adventures/ocean",
        link_name: "View Trips",
      },
    ],
    is_active: 1,
    image: "/images/lhotse.jpg",
    image_title: "Mountain Adventure",
    video_url: null,
  },
  {
    id: 3,
    display_order: 3,
    display_type: "video",
    title: "Experience the Ocean",
    subtitle: "Feel the Breeze",
    description: "Dive into crystal-clear waters and relax on pristine beaches.",
    link: [
      {
        slider_item_id: 2,
        link: "/adventures/ocean",
        link_name: "View Trips",
      },
    ],
    is_active: 1,
    image: null,
    image_title: "Mountain Adventure",
    video_url: "https://www.youtube.com/watch?v=e1_eZyFM5-4",
  },
//   {
//     id: 3,
//     display_order: 3,
//     display_type: "image",
//     title: "Cultural Journeys",
//     subtitle: "Tradition & Heritage",
//     description: "Immerse yourself in rich cultures, festivals, and ancient history.",
//     link: [
//       {
//         slider_item_id: 3,
//         link: "/journeys/culture",
//         link_name: "Learn More",
//       },
//     ],
//     is_active: 1,
//     image: "/images/slider/culture.jpg",
//     image_title: "Cultural Travel",
//     video_url: null,
//   },
//   {
//     id: 4,
//     display_order: 4,
//     display_type: "image",
//     title: "Wildlife Safaris",
//     subtitle: "Into the Wild",
//     description: "Get close to nature with guided wildlife safaris and eco tours.",
//     link: [
//       {
//         slider_item_id: 4,
//         link: "/tours/safari",
//         link_name: "Book Safari",
//       },
//     ],
//     is_active: 0,
//     image: "/images/slider/safari.jpg",
//     image_title: "Wildlife Safari",
//     video_url: null,
//   },
//   {
//     id: 5,
//     display_order: 5,
//     display_type: "video",
//     title: "Luxury Escapes",
//     subtitle: "Relax in Style",
//     description: "Indulge in premium resorts, spas, and exclusive experiences.",
//     link: [
//       {
//         slider_item_id: 5,
//         link: "/escapes/luxury",
//         link_name: "View Packages",
//       },
//     ],
//     is_active: 1,
//     image: null,
//     image_title: null,
//     video_url: "https://example.com/videos/luxury.mp4",
//   },
//   {
//     id: 6,
//     display_order: 6,
//     display_type: "image",
//     title: "City Breaks",
//     subtitle: "Urban Adventures",
//     description: "Discover vibrant cities filled with food, art, and nightlife.",
//     link: [
//       {
//         slider_item_id: 6,
//         link: "/trips/cities",
//         link_name: "See Cities",
//       },
//     ],
//     is_active: 1,
//     image: "/images/slider/city.jpg",
//     image_title: "City Travel",
//     video_url: null,
//   },
//   {
//     id: 7,
//     display_order: 7,
//     display_type: "image",
//     title: "Spiritual Retreats",
//     subtitle: "Peace & Mindfulness",
//     description: "Reconnect with yourself through serene retreats and meditation.",
//     link: [
//       {
//         slider_item_id: 7,
//         link: "/retreats/spiritual",
//         link_name: "Find Peace",
//       },
//     ],
//     is_active: 1,
//     image: "/images/slider/spiritual.jpg",
//     image_title: "Spiritual Retreat",
//     video_url: null,
//   },
];
